#  url = http://localhost:8000/api/v1/task

### get task
GET http://localhost:8000/api/v1/task/

### post task
POST http://localhost:8000/api/v1/task/
Content-Type: application/json

{
    "task": "watching tv",
    "hr": 33
}